services:
  snapserver:
    image: clcain/snapserver
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./snapserver/snapserver.conf:/etc/snapserver.conf:ro
    env_file:
      - .env
