version: '3'

services:

  airplay:
    build: ./airplay
    restart: on-failure
    network_mode: host
    volumes:
      - snapcast:/var/cache/snapcast
    env_file:
      - .env

  librespot:
    build: ./librespot
    restart: on-failure
    network_mode: host
    volumes:
      - snapcast:/var/cache/snapcast
    env_file:
      - .env

  snapserver:
    build: ./snapserver
    restart: on-failure
    network_mode: host
    volumes:
      - snapcast:/var/cache/snapcast
    env_file:
      - .env

volumes:
  snapcast:
